version: "3.8"

services:
  api:
    image: tickets-api
    command: "ts-node server.js"
    build:
      context: .
    volumes:
      - .:/app/
      - /app/node_modules
      - ./config:/app/config
    restart: unless-stopped
    ports:
      - "3000:3000"
